nina-protocol/nina

js/soft-lp/src/components/Exchange.js
empty messages were being sent to snackbar on exchange create and accept exchange completed from input
=> fix empty msg snackbars on Exchange actions

js/nina-common/src/components/ExchangeList.js, js/nina-common/src/contexts/exchange.js, js/web/src/components/ReleaseTabs.js
=> Pass Metadata to Exchange

js/nina-common/src/components/BuySellForm.js, js/nina-common/src/components/Exchange.js, js/nina-common/src/components/ExchangeHistoryModal.js, js/nina-common/src/components/ExchangeList.js, js/nina-common/src/components/ExchangeListItem.js, js/nina-common/src/components/RedeemableClaimForm.js, js/nina-common/src/components/RedeemableInitializeForm.js, js/nina-common/src/components/RedeemableUpdateShippingForm.js, js/nina-common/src/components/ReleaseSettings.js, js/nina-common/src/components/Royalty.js, js/nina-common/src/components/RoyaltyRecipientForm.js, js/nina-common/src/contexts/audio.js, js/nina-common/src/contexts/release.js, js/nina-common/src/utils/client.js, js/nina-common/src/utils/metaplex/metadata.js, js/web/package.json, js/web/src/components/AudioPlayer.js, js/web/src/components/Breadcrumbs.js, js/web/src/components/NavBar.js, js/web/src/components/QueList.js, js/web/src/components/RecentlyPublished.js, js/web/src/components/RecentlyPurchased.js, js/web/src/components/Release.js, js/web/src/components/ReleaseListTable.js, js/web/src/components/ReleasePurchase.js, js/web/src/routes.js, js/yarn.lock
Also styled the title in the Nav
=> Breadcrumbs

js/web/src/components/ReleaseListTable.js
=> Release list table sort

js/nina-common/src/components/BuySell.js, js/nina-common/src/components/BuySellForm.js, js/nina-common/src/components/Exchange.js, js/nina-common/src/components/ExchangeHistoryModal.js, js/nina-common/src/components/ExchangeList.js, js/nina-common/src/components/ExchangeModal.js, js/nina-common/src/components/ReleaseSettings.js, js/nina-common/src/utils/errors.js, js/soft-lp/src/components/Footer.js, js/web/package.json, js/web/src/NinaTheme.js, js/web/src/components/AudioPlayer.js, js/web/src/components/Breadcrumbs.js, js/web/src/components/HomePage.js, js/web/src/components/MobileWalletModal.js, js/web/src/components/NavBar.js, js/web/src/components/NavDrawer.js, js/web/src/components/NinaBox.js, js/web/src/components/QueueList.js, js/web/src/components/RecentlyPublished.js, js/web/src/components/RecentlyPurchased.js, js/web/src/components/Release.js, js/web/src/components/ReleaseCard.js, js/web/src/components/ReleaseListTable.js, js/web/src/components/ReleasePurchase.js, js/web/src/routes.js, js/yarn.lock
=> Pre launch tweaks

js/nina-common/src/components/BuySell.js, js/web/src/components/AllReleases.js, js/web/src/components/Breadcrumbs.js, js/web/src/components/FaqPage.js, js/web/src/components/HomePage.js, js/web/src/components/NavDrawer.js, js/web/src/components/RecentlyPublished.js, js/web/src/components/RecentlyPurchased.js, js/web/src/components/ReleaseListTable.js, js/web/src/components/ScrollablePageWrapper.js, js/web/src/routes.js
=> Ui updates

js/web/src/components/QueueList.js, js/web/src/components/ReleaseListTable.js, js/web/src/components/ReleasePurchase.js
allows mobile drag scrolling on release lists
=> All releases mobile

js/nina-common/src/components/Exchange.js, js/web/src/NinaTheme.js, js/web/src/components/AllReleases.js, js/web/src/components/FaqPage.js, js/web/src/components/NavDrawer.js, js/web/src/components/RecentlyPurchased.js, js/web/src/components/ReleaseCard.js, js/web/src/components/ReleaseListTable.js, js/web/src/components/ReleasePurchase.js
- reduced `h4` element to allow artist name + title to fit in info boxes on mobile
- shrunk `img` in exchange info box
- added bottom padding to allow more accessible `allReleases` view on mobile
- added ig button to navDrawer
=> Mobile Ui Tweaks

js/soft-lp/src/components/Footer.js, js/web/src/components/FaqPage.js, js/web/src/components/ReleaseList.js
-faq entry regarding off-ramping 
- link to faq in releaseList
=> withdrawal faq

js/nina-common/src/contexts/release.js, js/web/src/components/ReleaseCreate.js, js/web/src/components/ReleaseCreateForm.js
- closes #86 
- change default resalePercentage to 0
=> reset pressingState on cancelled TX

js/web/src/components/ReleasePurchase.js
=> overflow-wrap

js/nina-common/src/contexts/release.js, js/web/src/components/Release.js, js/web/src/components/ReleaseRelated.js, js/web/src/components/ReleaseTileList.js
optimizations to get us out of bad habit of fetching all releases - too many releases currently to keep doing this
=> Optimizations

js/nina-common/src/contexts/connection.js, js/nina-common/src/contexts/release.js, js/web/src/components/AllReleases.js
only get last 20 releases for recent - next step will be pagination on the allReleases
=> Recent limit

js/web/src/NinaTheme.js, js/web/src/components/MediaDropzone.js
related to #95
- limit imgs bigger than 4mb
- flexible error handling for dropzones
=> limit file size, flexible validation errors

js/web/src/components/RecentlyPublished.js
simple n easy solution to the recently published list getting spammed with multiple releases by same artist w/ same cover
=> Recently published stack

js/web/package.json, js/web/src/components/AllReleases.js, js/yarn.lock
Kind of hacky temporary solution:
if on mobile reverse the order of the all releases list
=> reverse order of all releases if on mobile

js/nina-common/src/contexts/audio.js, js/web/components/ReleaseCard.js, js/web/components/ReleaseTileList.js
stopgap to prevent very long artist / titles beyond conditions we could have foreseen
limit display of artist and title w/ substring(0, 100) - not a permanent fix but good for now
=> Title overflow

js/web/components/ReleasePurchase.js
temporarily hide release description on mobile
=> mobile style

js/web/components/Layout.js, js/web/components/NinaBox.js, js/web/components/Release.js
better handling of high level containers for mobile responsiveness
=> Mobile redesign

js/web/components/AllReleases.js, js/web/components/FaqPageContent.js, js/web/components/Image.js, js/web/components/NavDrawer.js, js/web/next.config.js
better scroll behavior for lazy loading
=> new handle scroll on allreleases

js/web/components/ReleaseCreateForm.js, js/web/next.config.js
-  10% initial value to resale slider
- show warning about 20%
=> resale percent warning;

js/sdk/src/contexts/nina.js, js/sdk/src/utils/errors.js, js/web/components/ReleaseCreate.js, js/web/components/ReleasePurchase.js
- nina error handler return value set to undefing
- upload manager implemented
=> Snackbar bugs

js/hubs/components/AddToHubModal.js, js/hubs/components/HubCollaborators.js, js/hubs/components/HubPostCreate.js, js/hubs/next.config.js, js/web/components/AddToHubModal.js, js/web/components/HubPostCreate.js, js/web/next.config.js
=> fix repost crash + fix collaborator active selection

js/hubs/components/AudioPlayer.js, js/hubs/components/ContentTileView.js, js/hubs/components/PostRelease.js, js/hubs/components/Release.js, js/hubs/next.config.js
closes #323 
+ add pause icon on content tile view if playing
=> fix player bugs

js/hubs/components/HubSlider.js, js/hubs/components/Hubs.js, js/hubs/components/Navigation.js, js/hubs/components/Quill.js, js/hubs/next.config.js
- fix featured Hub slider (wasnt fetching if connected wallet has no hubs)
- always show 'start exploring' on hubs homepage
=> Hubs hp bug

js/hubs/.gitignore, js/hubs/components/ContentTileView.js, js/hubs/components/Hub.js, js/hubs/components/HubOverview.js, js/hubs/components/Hubs.js, js/hubs/components/Navigation.js, js/hubs/components/Release.js, js/hubs/components/ReleaseCreateConfirm.js, js/hubs/components/ReleaseListTable.js, js/hubs/next.config.js, js/hubs/pages/[hubPubkey]/releases/[hubReleasePubkey]/index.js, js/hubs/pages/_app.js, js/hubs/pages/_error.js, js/hubs/sentry.client.config.js, js/hubs/sentry.properties, js/hubs/sentry.server.config.js, js/package.json, js/sdk/src/contexts/hub.js, js/web/.gitignore, js/web/components/HomePage.js, js/web/next.config.js, js/web/pages/_error.js, js/web/sentry.client.config.js, js/web/sentry.properties, js/web/sentry.server.config.js, js/yarn.lock
* shuffle-featured
* fix hub overview bug
=> Hub overview (#331)

js/hubs/components/ContentTileView.js, js/hubs/next.config.js
closes #335 
- fixes padding on bottom of images in contentTileView
- proper responsiveness on grid
- add consistent spacing on right of grid (to match 'all hubs' view)
=> Tile border bug

js/hubs/components/AllHubs.js, js/hubs/components/ContentTileView.js, js/hubs/components/Hub.js, js/hubs/components/Post.js, js/sdk/src/contexts/Hub/hub.js
closes #349 
closes #346 
closes #347
=> All Hubs Scroll - ContentTileView Border + Play Fixes

js/hubs/components/ReleaseCreateConfirm.js, js/hubs/components/ReleaseCreateViaHub.js, js/sdk/package.json, js/sdk/src/contexts/Release/release.js, js/sdk/src/utils/index.js, js/web/components/ReleaseCreate.js, js/web/components/ReleaseCreateConfirm.js, js/yarn.lock
=> Release Confirmation + Track MD5 verification

js/NinaTheme.js, js/hubs/components/AudioPlayer.js, js/hubs/components/ContentTileView.js, js/hubs/components/Hub.js, js/hubs/components/HubCreate.js, js/hubs/components/HubsModal.js, js/hubs/components/Layout.js, js/hubs/components/Navigation.js, js/hubs/components/Post.js, js/hubs/components/PostRelease.js, js/hubs/components/Release.js, js/hubs/components/ReleaseCreateConfirm.js, js/hubs/components/ReleasePurchase.js, js/hubs/next.config.js, js/hubs/styles/theme/lightThemeOptions.js, js/sdk/src/contexts/Audio/audio.js, js/sdk/src/contexts/Hub/hub.js, js/sdk/src/utils/imageManager.js, js/sdk/src/utils/index.js, js/web/components/ReleaseCreateConfirm.js, js/web/components/ReleasePurchase.js, js/web/next.config.js
=> Hubs - Seek + extend CDN delay + Hub Create correct link + navigation between hubs improvements

js/hubs/components/ColorModal.js, js/hubs/components/HubCreate.js, js/hubs/next.config.js
closes #361 
- add hexCode color pickers to hob create / update
- include color values in metadata on hubCreate
=> Hub hexcodes

js/web/components/Quill.js, js/web/components/ReleasePurchase.js
=> hide scroll

js/hubs/components/PostRelease.js, js/hubs/components/Release.js
=> hide scrollbars

js/hubs/components/AddToHubModal.js, js/hubs/components/HubAddCollaborator.js, js/hubs/components/HubAddRelease.js, js/hubs/components/HubCollaborators.js, js/hubs/components/HubCreate.js, js/hubs/components/HubPostCreate.js, js/hubs/components/ReleaseCreateViaHub.js, js/hubs/components/ReleasePurchase.js, js/hubs/components/Royalty.js, js/hubs/next.config.js, js/hubs/pages/[hubPubkey]/posts/[hubPostPubkey]/index.js, js/hubs/pages/[hubPubkey]/releases/[hubReleasePubkey]/index.js, js/sdk/src/contexts/Nina/nina.js, js/sdk/src/utils/errors.js, js/web/components/AddToHubModal.js, js/web/components/Exchange.js, js/web/components/HomePage.js, js/web/components/HubPostCreate.js, js/web/components/ReleaseCreate.js, js/web/components/ReleasePurchase.js, js/web/components/Royalty.js, js/web/next.config.js
closes #394 
closes #392 
closes #391 
closes #376
=> Error handling

js/hubs/components/AddToHubModal.js, js/hubs/components/HubAddCollaborator.js, js/hubs/components/HubAddRelease.js, js/hubs/components/HubCollaborators.js, js/hubs/components/HubCreate.js, js/hubs/components/HubPostCreate.js, js/hubs/components/ReleaseCreateViaHub.js, js/hubs/components/ReleasePurchase.js, js/hubs/components/Royalty.js, js/hubs/pages/[hubPubkey]/posts/[hubPostPubkey]/index.js, js/hubs/pages/[hubPubkey]/releases/[hubReleasePubkey]/index.js, js/sdk/src/contexts/Nina/nina.js, js/sdk/src/utils/errors.js, js/web/components/AddToHubModal.js, js/web/components/Exchange.js, js/web/components/HomePage.js, js/web/components/HubPostCreate.js, js/web/components/ReleaseCreate.js, js/web/components/ReleasePurchase.js, js/web/components/Royalty.js, js/web/next.config.js
* add back revenue share recipient
* Put actual price of Release + upload on the Homepage
* Define Program Actions
* use arweave chunked uploader
* fix sdk import
* inform user if they dont have enough sol for tx cost
* fix display of upload cost on homepage
* mainnet
=> Error handling (#393)

js/hubs/components/ContentTileView.js, js/hubs/components/HubImageDropzone.js, js/hubs/components/Royalty.js, js/hubs/next.config.js, js/web/.env, js/web/components/MediaDropzone.js
closes #412 
closes #401 
closes #389
=> img limit to 8mb

js/sdk/src/contexts/Nina/nina.js, js/web/components/FeedDrawer.js, js/web/components/Hub.js, js/web/components/ReusableTable.js, js/web/pages/_app.js, js/web/pages/hubs/[hubPubkey]/index.js
- add followers to table to Hub view
- move Hub metadata to `page` file
=> Hub followers

js/hubs/components/EmailCapture.js, js/hubs/components/Hubs.js, js/web/components/EmailCapture.js, js/web/components/EmailCaptureForm.js, js/web/components/Feed.js, js/web/components/FeedDrawer.js, js/web/components/Suggestions.js, js/web/utils/identityVerification.js
- closes #506 #504
- drawer mobile style
- mobile styling for email capture
=> Navigator mobile + email capture style

js/hubs/components/EmailCapture.js, js/web/components/Feed.js, js/web/components/FeedDrawer.js, js/web/components/Layout.js
=> overflow bug

js/web/components/NavSearch.js, js/web/components/ReusableTable.js, js/web/components/Search.js, js/web/components/SearchDropdown.js
- Closes #519 
- Closes #520
- Closes #525 
- Closes #530
=> Search dropdown

js/hubs/components/EmailCapture.js, js/web/components/EmailCapture.js, js/web/components/FeedDrawer.js, js/web/components/NavSearch.js, js/web/components/Search.js
- closes #518
- add maxWidth to navigator drawer
- navbar component styling (search input and Sign Up CTA)
=> Navigator style

js/web/components/Dashboard.js, js/web/components/DashboardWelcome.js
=> Dashboard modal

js/web/components/EmailCapture.js, js/web/components/HomePage.js
=> Homepage copy

js/web/components/DashboardWelcome.js, js/web/components/Feed.js, js/web/components/IdentityVerification.js, js/web/components/NavSearch.js, js/web/components/Profile.js, js/web/components/Search.js, js/web/components/TabHeader.js, js/web/components/UploadInfoModal.js, js/web/pages/[releasePubkey]/related.js, js/web/utils/identityVerification.js
- Closes #544 
- Closes #543 
- Closes #541
=> Play releases tab

js/sdk/src/contexts/Nina/nina.js, js/web/components/Profile.js, js/web/components/Search.js
=> fix new account state

js/web/components/FeedDrawer.js, js/web/components/IdentityVerification.js, js/web/components/Profile.js, js/web/components/ReusableTable.js, js/web/components/TabHeader.js
-closes #524 #527 #542 
- break long numbers so collect button doesnt get cutoff
- give SVGs in connect explicit height so they dont disappear
=> Dashboard Bugs

js/hubs/components/HubOverview.js, js/sdk/src/contexts/Nina/nina.js, js/web/components/Profile.js, js/web/components/Subscribe.js, js/yarn.lock
=> Hub player UI fix

js/hubs/components/HubCreate.js, js/sdk/src/contexts/Hub/hub.js, js/sdk/src/contexts/Nina/nina.js, js/web/components/Hub.js, js/web/components/Subscribe.js, js/web/components/Suggestions.js
=> Hub Form Style + Unfollow Bug

js/hubs/components/HubCreate.js, js/sdk/src/contexts/Hub/hub.js
=> Hub create button

js/hubs/components/AddToHubModal.js, js/web/components/AddToHubModal.js, js/web/components/FeedDrawer.js
- add wallet conditionto `addToHubsModal`
=> wallet check for hub request

js/hubs/pages/create.js, js/web/components/FeedDrawer.js, js/web/components/NavDrawer.js, js/web/components/ReusableTable.js, js/web/components/Search.js, js/web/pages/[releasePubkey]/related.js
=> Search icon

js/sdk/src/contexts/Exchange/exchange.js, js/web/components/Exchange.js, js/web/components/ExchangeHistoryModal.js, js/web/components/ExchangeListItem.js
=> Exchange fixes

js/web/components/ReusableTable.js, js/web/components/Search.js
- Closes #621 
- Closes #622 
- Closes #623 
- Closes #627
=> Reusable table widths

js/web/components/Feed.js, js/web/components/FeedDrawer.js
=> feed refresh on subscription change

js/sdk/src/contexts/Exchange/exchange.js, js/sdk/src/contexts/Release/release.js, js/web/components/Exchange.js, js/web/components/ExchangeHistoryModal.js, js/web/components/ExchangeListItem.js, js/web/components/Profile.js
=> Profile colleciton playlist

js/web/components/ExchangeHistoryModal.js, js/web/components/ExchangeListItem.js, js/web/components/Profile.js, js/web/components/ReusableTable.js, js/web/components/Search.js
- Closes #636 
- Removes unused vars and adds dynamic import for profiles, hubs, and search
=> Search submit

js/hubs/components/Hubs.js, js/hubs/next.config.js, js/hubs/package.json, js/hubs/pages/_app.js, js/sdk/src/contexts/Nina/nina.js, js/web/components/EmailCapture.js, js/web/components/Feed.js, js/web/components/FeedDrawer.js, js/web/components/HubHeader.js, js/web/components/HubSlider.js, js/web/components/Profile.js, js/web/components/RecentlyPublished.js, js/web/components/ReleaseCreate.js, js/web/components/ReusableTable.js, js/web/next.config.js, js/web/package.json, js/web/pages/_app.js, js/yarn.lock
- closes #643
- closes #645
- add BackpackWalletAdapter
=> Style tweaks

js/web/components/ExchangeHistoryModal.js, js/web/components/ExchangeListItem.js, js/web/components/FeedDrawer.js, js/web/components/Layout.js, js/web/components/NavBar.js, js/web/components/NavSearch.js
=> Render search above Navigator

js/hubs/components/AllHubs.js, js/hubs/components/HubSlider.js, js/hubs/components/HubTileView.js, js/hubs/components/Layout.js, js/hubs/components/NavBar.js, js/hubs/pages/[hubPubkey]/index.js, js/hubs/pages/[hubPubkey]/posts/[hubPostPubkey]/index.js, js/hubs/pages/[hubPubkey]/releases/[hubReleasePubkey]/index.js, js/sdk/src/contexts/Nina/nina.js, js/sdk/src/contexts/Release/release.js, js/web/components/HubSlider.js, js/web/components/IdentityVerification.js, js/web/components/ReleaseCreate.js, js/web/components/ReusableTable.js, js/web/pages/[releasePubkey]/index.js, js/web/pages/[releasePubkey]/market.js, js/web/pages/hubs/[hubPubkey]/index.js, js/web/pages/hubs/index.js, js/web/pages/profiles/[profilePubkey]/index.js
=> Highlights + Hubs fixes

js/web/components/EmailCapture.js, js/web/components/ReusableTable.js
=> Realign follow

js/hubs/components/BundlrModal.js, js/web/components/BundlrModal.js
=> Bundlr Default Value

js/web/components/TabHeader.js
=> Tab Header Style Bug

js/web/components/Hub.js, js/web/components/Profile.js
Fix dependency array in profiles and hubs default active view setting
=> Follow Active View Bug

js/sdk/src/contexts/Nina/nina.js
Remove healthCheck function due to extraneous requests
=> Remove Healthcheck

Anchor.toml, Cargo.lock, programs/nina/Cargo.toml, programs/nina/src/instructions/mod.rs, programs/nina/src/instructions/release_close_edition.rs, programs/nina/src/instructions/release_init_with_credit.rs, programs/nina/src/instructions/release_update_metadata.rs, programs/nina/src/lib.rs, programs/nina/src/state/release.rs, tests/index.js, tests/utils/index.js
=> Mutable metadata

js/web/components/FeedDrawer.js
-filter buggy `ReleaseInitViaHub` items
=> filter bad feedItems

js/hubs/components/EmailCapture.js, js/hubs/components/MediaDropzone.js, js/hubs/components/Post.js, js/hubs/components/QuillEditor.js, js/hubs/components/ReleaseCreateViaHub.js, js/web/components/HubPostCreateForm.js, js/web/components/QuillEditor.js
=> Post UI bugs

js/hubs/components/ReleasePurchase.js, js/web/components/ReleaseCard.js, js/web/components/ReleasePurchase.js
say 'free' when price is zero on releases
=> Release Purchase Button Copy

js/web/components/HubHeader.js, js/web/components/Profile.js
=> Fix Hub Create CTA

js/sdk/src/contexts/Release/release.js
=> Release purchase cta bug

js/web/components/Profile.js, js/web/components/ReleaseCard.js, js/web/components/ReusableTable.js
=> Download in table

js/hubs/components/AudioPlayer.js, js/hubs/components/HubOverview.js, js/hubs/components/HubPosts.js, js/hubs/components/HubReleases.js, js/hubs/components/Hubs.js, js/hubs/components/HubsModal.js, js/hubs/components/NavBar.js, js/hubs/components/NotFound.js, js/hubs/components/ReleaseSettings.js, js/hubs/styles/theme/lightThemeOptions.js, js/sdk/src/components/ReleaseCreate.js, js/sdk/src/utils/openInNewTab.js, js/web/components/AudioPlayer.js, js/web/components/CollectorModal.js, js/web/components/CreateHub.js, js/web/components/ExchangeHistoryModal.js, js/web/components/Feed.js, js/web/components/HomePage.js, js/web/components/HubsModal.js, js/web/components/NavBar.js, js/web/components/NavDrawer.js, js/web/components/NotFound.js, js/web/components/ReleaseList.js, js/web/components/Releases.js, js/web/components/ReusableTable.js, js/web/components/Suggestions.js
=> Clickout table

js/package.json, js/sdk/src/client.js, js/sdk/src/components/ReleaseCreate.js, js/sdk/src/components/ReleaseCreateConfirm.js, js/sdk/src/components/ReleaseCreateForm.js, js/sdk/src/contexts/Exchange/exchange.js, js/sdk/src/contexts/Release/release.js, js/sdk/src/utils/releasePurchaseHelper.js, js/sdk/src/utils/web3.js, js/web/components/ExchangeListItem.js, js/web/components/ReleasePurchase.js
- whitelist COH to publish releases in SOL
=> Sol purchase

js/sdk/src/utils/cropImage.js
- tweaked Canvas cropper code to retain original image dimensions + fileSize
- closes #877
=> Cropper audit

js/hubs/components/ReleasePurchase.js, js/sdk/src/components/GateUnlockModal.js, js/sdk/src/components/Gates.js, js/web/components/HubHeader.js, js/web/components/HubsModal.js, js/web/components/ReleaseCard.js, js/web/components/ReleasePurchase.js, js/web/package.json, js/yarn.lock
- santize HTML in hub header 
- improve desciption styling
-
=> sanitize hubHeader descriptions in web

js/web/components/ReusableTable.js
- remove `Link` from release name in table
=> Table link fix

js/hubs/components/Post.js
=> Post style

js/hubs/components/AudioPlayer.js, js/sdk/src/contexts/Audio/audio.js
=> links in audioplayer point to correct post and release links

js/hubs/components/ReleaseSettings.js, js/sdk/src/components/GateCreateModal.js, js/sdk/src/components/GateManageModal.js, js/sdk/src/components/GateUnlockModal.js, js/sdk/src/components/ShareToTwitter.js, js/web/components/NewProfileCtas.js
=> Gates modal fix

js/web/components/LearnMore.js, js/web/components/ReleaseTileList.js
=> Releases new tab

js/web/components/ReleaseTileList.js
=> fixed play button bug

js/NinaTheme.js, js/hubs/components/Release.js, js/web/components/ReleasePurchase.js
=> fixed css handling for pre tags and width of description box

js/sdk/src/components/EmailLoginForm.js, js/sdk/src/components/EmailOTPForm.js, js/sdk/src/components/IdentityVerification.js, js/sdk/src/components/RedeemReleaseCode.js, js/sdk/src/components/SwapModal.js, js/sdk/src/components/WalletConnectModal.js, js/sdk/src/contexts/Nina/nina.js, js/sdk/src/contexts/Release/release.js, js/sdk/src/utils/swap.js, js/web/components/HomePage.js, js/web/components/ReleasePurchase.js
=> redeem release code centers on own and with gates copy in hubs and web

js/sdk/src/components/NoSolWarning.js
=> Ez modal update

js/sdk/src/components/IdentityVerification.js, js/sdk/src/components/ReleaseCreateForm.js
=> Ez eth hide

js/sdk/src/components/ReleaseCreateForm.js
- added a 'FREE' button inr elease create
=> free button

js/sdk/src/components/ReleaseCreateSuccess.js
=> pass releasePubkey prop

js/web/components/Onboard.js
=> pendingtransactionmessage imported into onboard

js/sdk/src/components/ReleaseCreate.js
=> Low balance bug

js/hubs/components/HubPosts.js, js/sdk/src/components/AddToHubModal.js, js/sdk/src/components/HubPostCreate.js, js/sdk/src/components/HubPostCreateForm.js
=> text post fix

js/sdk/src/contexts/Nina/nina.js
will provide forward compatibility with program updates address in #1005 
can be merged to main in advance of that
=> add payer to subscription_* methods

js/sdk/src/components/Swap.js, js/sdk/src/contexts/Exchange/exchange.js, js/sdk/src/contexts/Nina/nina.js, js/sdk/src/utils/swap.js
closes #1016, #1017
- UI was not reflecting new balances after successful swap.
=> Fix Swap UI

js/sdk/src/components/HubPostCreate.js, js/sdk/src/contexts/Nina/nina.js, js/sdk/src/utils/errors.js
closes #1022 
we probably want to fix this more thoroughly so that we calculate the size of the json before attempting to upload the post so that we can give the user better feedback 
also maybe if the upload account is below a certain balance we display it in red or yellow to bring the users attention to it?
=> Ez low upload error

js/sdk/src/components/HubPostCreate.js
=> Hubs hub post fix

js/sdk/src/components/HubCreateSuccess.js, js/sdk/src/contexts/Wallet/wallet.js
=> Ez copy fixes

js/sdk/src/contexts/Exchange/exchange.js, js/web/components/Exchange.js, js/web/components/ExchangeListItem.js, js/web/components/ExchangeModal.js, js/web/components/Profile.js
=> Ez exchange bug

js/hubs/next.config.js, js/sdk/src/components/Dots.js, js/sdk/src/components/HubCreate.js
=> Hub Update CTA Fix

js/sdk/src/components/HubPostCreate.js
=> skip hubPostRelease lookup if post has no release

js/sdk/src/components/HubCreate.js, js/sdk/src/components/HubCreateForm.js
=> Hub handle maxLength fix

js/sdk/src/contexts/Nina/nina.js, js/web/components/Balance.js, js/web/components/Profile.js, js/web/pages/profiles/[profilePubkey]/index.js
=> User balance lookup

js/web/components/ReusableTable.js
=> Collect revenue feedback

js/sdk/src/components/AddToHubModal.js
Update `add To Hub Modal` to link uesrs to the hubCreate page
=> update hub create link in addToHub modal

js/sdk/src/components/IdentityVerification.js
hide 'X' unless profile belongs to connected user
=> hide remove verification

js/web/components/NavBar.js
fix signup button font size on mobile
=> style signup button mobile

js/web/components/AllReleases.js
closes #1070
initial fetch was failing due to `program` being undefined in `NinaSdk.Release.fetchAll()`
=> All Release Page Bug

js/sdk/src/components/EmailCapture.js, js/sdk/src/components/IdentityVerification.js
- resolved mobile display for verification CTAs
=> fix mobile button padding

js/sdk/src/components/MediaDropzone.js, js/sdk/src/contexts/Nina/nina.js
- removed Image upload limit as it was causing problems + our images are chached and served from imgix
=> remove image size limit

js/sdk/src/components/ReleaseCreateForm.js
set 'unlimited' as default value in release create flow
=> default to open release

js/web/components/Admin.js, js/web/components/Onboard.js, js/web/package.json, js/web/pages/start/avyss.js, js/web/pages/start/index.js, js/yarn.lock
=> implemented japanese localization copy

js/web/components/Release.js, js/web/components/ReleasePurchase.js
=> padding bottom added to release description

js/sdk/src/components/CoinflowModal.js, js/sdk/src/components/PurchaseModal.js
- add Credit Card Icons to `pay with card` button
- style adjustments
=> Coinflow style

js/web/components/Onboard.js, js/web/pages/start/ikj.js, js/web/pages/start/nina-night.js
=> mobile onboard flow style

js/sdk/src/components/ReleaseCreate.js, js/sdk/src/contexts/Nina/nina.js
- force balance check on upload flow to handle unintended lowBalanceModal behavior
=> recheck on upload flow
